# Generated by Django 2.2 on 2019-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_no',
            field=models.BigIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='user',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=91),
        ),
    ]
