# Generated by Django 2.2 on 2020-03-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200311_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='pro.png', upload_to='profile/'),
        ),
    ]
