# Generated by Django 3.0.4 on 2020-03-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200328_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenprofile',
            name='canteen_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Not Assigned', max_length=20),
        ),
    ]
