# Generated by Django 2.2 on 2019-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(upload_to='food_image/'),
        ),
    ]
