# Generated by Django 2.2 on 2019-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191227_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='food_categoary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
