# Generated by Django 2.2 on 2019-12-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191227_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
