# Generated by Django 2.2 on 2019-12-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_categoary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Category'),
            preserve_default=False,
        ),
    ]
