# Generated by Django 3.0 on 2020-01-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='quant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
