# Generated by Django 3.0 on 2020-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20200121_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
