# Generated by Django 2.2 on 2020-02-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20200129_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
