# Generated by Django 2.2 on 2020-02-11 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0022_auto_20200211_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust', to=settings.AUTH_USER_MODEL),
        ),
    ]
