# Generated by Django 2.2 on 2020-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_myorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='time',
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
