# Generated by Django 2.2 on 2020-02-13 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0025_auto_20200211_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canteen', to=settings.AUTH_USER_MODEL),
        ),
    ]
