# Generated by Django 2.2 on 2020-02-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20200221_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Menu')),
            ],
        ),
    ]
