# Generated by Django 2.2 on 2020-02-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
