# Generated by Django 2.2 on 2020-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_delete_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
