# Generated by Django 2.2 on 2020-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='cust_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
