# Generated by Django 2.2 on 2020-03-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20200304_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='no_of_rating',
            field=models.IntegerField(default=0),
        ),
    ]
