# Generated by Django 2.2 on 2020-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
