# Generated by Django 3.0.2 on 2020-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_orders_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
