# Generated by Django 3.0.2 on 2020-03-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_auto_20200319_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('COD', 'COD'), ('Refund', 'Refund')], default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundId', models.CharField(max_length=30)),
                ('refund_date', models.DateField(auto_now_add=True)),
                ('refund_amount', models.IntegerField()),
                ('txnId', models.CharField(max_length=30)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Orders')),
            ],
        ),
    ]
