# Generated by Django 3.0.2 on 2020-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_20200319_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Accept', 'Accept'), ('Pending', 'Pending'), ('Reject', 'Reject'), ('Refund', 'Refund')], default='Pending', max_length=30),
        ),
    ]
