# Generated by Django 3.0.4 on 2020-03-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_auto_20200320_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
